### PR TITLE
Patcher failed dealing with interface or abstract class

### PR DESCRIPTION
**Pull request by kasimtan**

### CODE REVIEW

**Comment by kenjis** [comment]
You can't patch interfaces. What do you want?

**Comment by csksm** [comment]
I have some interface and abstract classes in my project.
Those cause errors when running ci-phpunit with MonkeyPatch enabled.

**Comment by kenjis** [comment]
I got you. Thank you for reporting!

**Comment by kenjis** [comment]
@kasimtan 
I pushed the fix: https://github.com/kenjis/ci-phpunit-test/commit/4a966eb75bae9080801f24f58293efc66cecbdc6

**Pull request merged**
