### PR TITLE
Changed the inheritor of `CIPHPUnitTestRequest`

### PR DESCRIPTION
**Pull request by ytetsuro**
TestCase -> CIPHPUnitTestCase

@see: https://github.com/kenjis/ci-phpunit-test/pull/254

### CODE REVIEW

**Comment by kenjis** [comment]
Why this PR is a test for it?

**Comment by ytetsuro** [comment]
constructor in CIPHPUnitTestCase is depends `TestCase`.
Because this PR code is should occur error.

**Comment by kenjis** [comment]
@ytetsuro This PR does not express the intent.

**Comment by kenjis** [comment]
I added the test for it: https://github.com/kenjis/ci-app-for-ci-phpunit-test/commit/194abe99550e1eb7735f579dc09860063afc0575

**Comment by ytetsuro** [comment]
> This PR does not express the intent.

informative.
Thank you very much.

**Pull request closed without merging**
